---
title: "plots_preppeddata_psychometrics"
author: "Martyna"
date: "2023-04-08"
output: html_document
---

```{r, echo = FALSE}
# Load necessary packages
library(ggplot2)
library(viridis)
library(RColorBrewer)
library(ggbeeswarm)
library(tidyr)
library(dplyr)
library(readr)

# Define a color palette
my_colors <- brewer.pal(3, "Set1")

# set working directory and upload dataset
setwd("~/dev/pregnancy_gaze")
df<- read_csv("table_ready_with_psycho.csv")
```

```{r}
# Create a new data frame with the variables of interest
new_data_long <- select(df, group, mean_peak_vel_anti, mean_peak_vel_pro) %>%
  pivot_longer(cols = c(mean_peak_vel_anti, mean_peak_vel_pro), names_to = "type", values_to = "mean_peak_vel") %>%
  mutate(type = ifelse(type == "mean_peak_vel_anti", "Antisaccade", "Prosaccade"))

new_data_long$group <- as.factor(new_data_long$group)
  
  
ggplot(new_data_long, aes(x = group, y = mean_peak_vel, fill = type)) +
  geom_violin(scale = "count", alpha = 0.4, trim = TRUE) +
  geom_violin(scale = "count", alpha = 0.4, trim = TRUE) +
  geom_point(width = 0.2, size = 2, alpha = 0.8, aes(color = type), position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) + # Separate jittered points  geom_boxplot(width = 0.15, alpha = 0.6, aes(color = type), position = position_dodge(0.8)) +
  scale_fill_manual(values = my_colors, name = "Saccade Type") +
  scale_color_manual(values = my_colors, name = "Saccade Type") + # Combine legends
  labs(x = "Group", y = "Mean Peak Velocity (degrees/second)", fill = "") +
  ggtitle("Distribution of Mean Peak Velocity by Group and Saccade Type") +
  theme_minimal() +
  theme(plot.title = element_text(size = 15, hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))


```

```{r}
# Creating a new data frame with the rt as var of interest
new_data_long <- select(df, group, mean_sacc_time_anti, mean_sacc_time_pro) %>%
  pivot_longer(cols = c(mean_sacc_time_anti, mean_sacc_time_pro), names_to = "type", values_to = "mean_sacc_time") %>%
  mutate(type = ifelse(type == "mean_sacc_time_anti", "Antisaccade", "Prosaccade"))

new_data_long$group <- as.factor(new_data_long$group)

# Create the plot
ggplot(new_data_long, aes(x = group, y = mean_sacc_time, fill = type)) +
    geom_violin(scale = "count", alpha = 0.4, trim = TRUE) +
  geom_point(width = 0.2, size = 2, alpha = 0.8, aes(color = type), 
             position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) + # Separate jittered points
  geom_boxplot(width = 0.15, alpha = 0.6, aes(color = type), position = position_dodge(0.8)) +
  scale_fill_manual(values = my_colors, name = "Saccade Type") +
  scale_color_manual(values = my_colors, name = "Saccade Type") + # Combine legends
  labs(x = "Group", y = "Mean Reaction Time (ms)") +
  ggtitle("Distribution of Mean Reaction Time by Group and Saccade Type") +
  theme_minimal() +
  theme(plot.title = element_text(size = 15, hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))

```

```{r}
# Create a new data frame with the errors pro/anti
new_data_long <- select(df, group, cum_errors_pro, cum_errors_anti) %>%
  pivot_longer(cols = c(cum_errors_pro, cum_errors_anti), names_to = "type", values_to = "cum_errors") %>%
  mutate(type = ifelse(type == "cum_errors_anti", "Antisaccade", "Prosaccade"))

new_data_long$group <- as.factor(new_data_long$group)

# Create the plot
ggplot(new_data_long, aes(x = group, y = cum_errors, fill = type)) +
  geom_violin(scale = "count", alpha = 0.4, trim = TRUE) +
  geom_point(width = 0.2, size = 2, alpha = 0.8, aes(color = type), 
             position = position_jitterdodge(jitter.width = 0.2, dodge.width = 0.8)) + # Separate jittered points
  geom_boxplot(width = 0.15, alpha = 0.6, aes(color = type), position = position_dodge(0.8)) +
  scale_fill_manual(values = my_colors, name = "Saccade Type") +
  scale_color_manual(values = my_colors, name = "Saccade Type") +
  labs(x = "Group", y = "Cumulative Errors") + # Update y-axis label
  ggtitle("Distribution of Cumulative Errors by Group and Saccade Type") +
  theme_minimal() +
  theme(plot.title = element_text(size = 15, hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))

```

# PSYCHOMETRICS

```{r}
# Create a new data frame with the variables of interest
new_data_long <- select(df, group, EPDS_SUM, cum_errors_pro, cum_errors_anti) %>%
  pivot_longer(cols = c(cum_errors_pro, cum_errors_anti), names_to = "type", values_to = "cum_errors") %>%
  mutate(type = ifelse(type == "cum_errors_anti", "Antisaccade", "Prosaccade"))

new_data_long$group <- as.factor(new_data_long$group)

# Calculate Spearman correlation coefficients for each combination of saccade type and group
correlations <- new_data_long %>%
  group_by(type, group) %>%
  summarize(spearman_rho = cor.test(EPDS_SUM, cum_errors, method = "spearman")$estimate)

# Print the correlations
print(correlations)

# Create the plot
ggplot(new_data_long, aes(x = EPDS_SUM, y = cum_errors, color = type, group = interaction(type, group))) +
  geom_point(size = 3, alpha = 0.8, aes(shape = group)) +
  geom_smooth(method = "lm", se = FALSE, aes(linetype = group)) + # Fit a regression line
  scale_color_manual(values = my_colors, name = "Saccade Type") +
  labs(x = "EPDS_SUM (Depression Scale)", y = "Cumulative Errors") +
  ggtitle("Correlation of Cumulative Errors and EPDS_SUM by Saccade Type and Group") +
  theme_minimal() +
  theme(plot.title = element_text(size = 15, hjust = 0.5),
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 12),
        legend.title = element_text(size = 14),
        legend.text = element_text(size = 12))

```

